export const routes = {
  login: "/auth/login",
  registro: "/auth/registro",
  miPerfil: "/miPerfil",
  carroCompras: "/carroCompra",
  home: "/",
  nosotros: "/nosotros",
  favoritos: "/planesRutinas/favoritos",
  planesRutinas: "/planesRutinas",
  casosExito: "/casosExito",
  tarifas: "/tarifas",
  eventos: "/eventos",
  Comunidad: "/comunidad",
  admin: "/admin",
  adminU: "/admin/usuarios",
  adminE: "/admin/eventos",
  adminRes: "/admin/reservas",
  adminR: "/admin/rutinas",
  adminEn: "/admin/entrenadores",
  adminP: "/admin/publicidad",
  adminCE: "/admin/casosDeExito",
  misEventos: "/eventos/misReservas",
  comunidad: "/comunidad",
  chat: "/comunidad#mobile-widget",
};
