import React from "react";

import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "../app/styles/globals.css";
import { Bounce, ToastContainer } from "react-toastify";
import Navbar from "./components/navbarFooter/navbar";
import Footer from "./components/navbarFooter/footer";
import { AuthProvider } from "./contextos/contextoAuth";
import VisibleWrapper from "./wrapper/visibleWrapper";
import Script from "next/script";
import { Elements } from "@stripe/react-stripe-js";
import { loadStripe } from "@stripe/stripe-js";
import { Providers } from "./providers";
import ClientWrapper from "./ClientWraper";

const stripePromise = loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLIC_KEY!);

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
}) as unknown as { variable: string };

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Xtreme Gym",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${poppins.variable} antialiased`}>
        {" "}
        <ClientWrapper>{children}</ClientWrapper>
        <script
          src="//code.tidio.co/d5nlufbj8mjvzlknyy2qjjfsgfyn9thb.js"
          async
        ></script>
      </body>
    </html>
  );
}
